version: '3.8'
services:
  db:
    build:
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres

  # docker run --rm --name mattermost-preview -d --publish 8065:8065 mattermost/mattermost-preview
  mattermost:
      image: mattermost/mattermost-preview
      restart: unless-stopped
      depends_on:
      - db
      ports:
      - "8065:8065"
      volumes:
      - ./data:/mattermost/data
volumes:
  db_data:
