name: Deploy Docsify to GitHub Pages

on:
  push:
    branches:
      - [main, workflow/*]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install docsify-cli
        run: npm install -g docsify-cli

      - name: Install gh-pages-multi
        run: npm install -g  @koumoul/gh-pages-multi

      - name: Build Docsify site
        run: docsify init ./

      - name: Generate sidebar based on directory structure
        run: node ./generateSidebar.js

      - name: Generate sidebar for v1.0
        run: |
          cd v1.0
          node ../generateSidebar.js
          cd ../v2.0
          node ../generateSidebar.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
