name: Deploy Docsify to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install docsify-cli
        run: npm install -g docsify-cli

      - name: Build Docsify site
        run: docsify init ./

      - name: Generate sidebar based on directory structure
        run: node ./generateSidebar.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
